-- Clear existing currencies
DELETE FROM [Mynt].[dbo].[Currencies];

-- Insert currencies with symbol positions
INSERT INTO [Mynt].[dbo].[Currencies] ([Code], [Name], [Symbol], [SymbolPosition], [IsSystemManaged], [CreatedById], [CreatedAt], [IsActive])
VALUES 
    ('USD', 'US Dollar', '$', 0, 1, NULL, GETUTCDATE(), 1),
    ('EUR', 'Euro', '€', 0, 1, NULL, GETUTCDATE(), 1),
    ('GBP', 'British Pound', '£', 0, 1, NULL, GETUTCDATE(), 1),
    ('JPY', 'Japanese Yen', '¥', 0, 1, NULL, GETUTCDATE(), 1),
    ('SEK', 'Swedish Krona', 'kr', 1, 1, NULL, GETUTCDATE(), 1),
    ('NOK', 'Norwegian Krone', 'kr', 1, 1, NULL, GETUTCDATE(), 1),
    ('DKK', 'Danish Krone', 'kr', 1, 1, NULL, GETUTCDATE(), 1),
    ('CHF', 'Swiss Franc', 'CHF', 0, 1, NULL, GETUTCDATE(), 1),
    ('CAD', 'Canadian Dollar', 'C$', 0, 1, NULL, GETUTCDATE(), 1),
    ('AUD', 'Australian Dollar', 'A$', 0, 1, NULL, GETUTCDATE(), 1),
    ('CNY', 'Chinese Yuan', '¥', 0, 1, NULL, GETUTCDATE(), 1),
    ('INR', 'Indian Rupee', '₹', 0, 1, NULL, GETUTCDATE(), 1),
    ('BRL', 'Brazilian Real', 'R$', 0, 1, NULL, GETUTCDATE(), 1),
    ('MXN', 'Mexican Peso', '$', 0, 1, NULL, GETUTCDATE(), 1),
    ('KRW', 'South Korean Won', '₩', 0, 1, NULL, GETUTCDATE(), 1),
    ('SGD', 'Singapore Dollar', 'S$', 0, 1, NULL, GETUTCDATE(), 1),
    ('HKD', 'Hong Kong Dollar', 'HK$', 0, 1, NULL, GETUTCDATE(), 1),
    ('NZD', 'New Zealand Dollar', 'NZ$', 0, 1, NULL, GETUTCDATE(), 1),
    ('PLN', 'Polish Złoty', 'zł', 0, 1, NULL, GETUTCDATE(), 1),
    ('CZK', 'Czech Koruna', 'Kč', 0, 1, NULL, GETUTCDATE(), 1),
    ('HUF', 'Hungarian Forint', 'Ft', 0, 1, NULL, GETUTCDATE(), 1),
    ('RUB', 'Russian Ruble', '₽', 0, 1, NULL, GETUTCDATE(), 1),
    ('TRY', 'Turkish Lira', '₺', 0, 1, NULL, GETUTCDATE(), 1),
    ('ZAR', 'South African Rand', 'R', 0, 1, NULL, GETUTCDATE(), 1),
    ('THB', 'Thai Baht', '฿', 0, 1, NULL, GETUTCDATE(), 1),
    ('MYR', 'Malaysian Ringgit', 'RM', 0, 1, NULL, GETUTCDATE(), 1),
    ('IDR', 'Indonesian Rupiah', 'Rp', 0, 1, NULL, GETUTCDATE(), 1),
    ('PHP', 'Philippine Peso', '₱', 0, 1, NULL, GETUTCDATE(), 1),
    ('VND', 'Vietnamese Dong', '₫', 0, 1, NULL, GETUTCDATE(), 1),
    ('EGP', 'Egyptian Pound', 'E£', 0, 1, NULL, GETUTCDATE(), 1),
    ('NGN', 'Nigerian Naira', '₦', 0, 1, NULL, GETUTCDATE(), 1),
    ('KES', 'Kenyan Shilling', 'KSh', 0, 1, NULL, GETUTCDATE(), 1),
    ('GHS', 'Ghanaian Cedi', 'GH₵', 0, 1, NULL, GETUTCDATE(), 1),
    ('UGX', 'Ugandan Shilling', 'USh', 0, 1, NULL, GETUTCDATE(), 1),
    ('TZS', 'Tanzanian Shilling', 'TSh', 0, 1, NULL, GETUTCDATE(), 1),
    ('ETB', 'Ethiopian Birr', 'Br', 0, 1, NULL, GETUTCDATE(), 1),
    ('MAD', 'Moroccan Dirham', 'MAD', 0, 1, NULL, GETUTCDATE(), 1),
    ('TND', 'Tunisian Dinar', 'TND', 0, 1, NULL, GETUTCDATE(), 1),
    ('LYD', 'Libyan Dinar', 'LYD', 0, 1, NULL, GETUTCDATE(), 1),
    ('DZD', 'Algerian Dinar', 'DZD', 0, 1, NULL, GETUTCDATE(), 1),
    ('XOF', 'West African CFA Franc', 'CFA', 0, 1, NULL, GETUTCDATE(), 1),
    ('XAF', 'Central African CFA Franc', 'FCFA', 0, 1, NULL, GETUTCDATE(), 1),
    ('XCD', 'East Caribbean Dollar', 'EC$', 0, 1, NULL, GETUTCDATE(), 1),
    ('JMD', 'Jamaican Dollar', 'J$', 0, 1, NULL, GETUTCDATE(), 1),
    ('TTD', 'Trinidad and Tobago Dollar', 'TT$', 0, 1, NULL, GETUTCDATE(), 1),
    ('BBD', 'Barbadian Dollar', 'Bds$', 0, 1, NULL, GETUTCDATE(), 1),
    ('BZD', 'Belize Dollar', 'BZ$', 0, 1, NULL, GETUTCDATE(), 1),
    ('GYD', 'Guyanese Dollar', 'G$', 0, 1, NULL, GETUTCDATE(), 1),
    ('SRD', 'Surinamese Dollar', 'SRD', 0, 1, NULL, GETUTCDATE(), 1),
    ('CLP', 'Chilean Peso', 'CL$', 0, 1, NULL, GETUTCDATE(), 1),
    ('COP', 'Colombian Peso', 'CO$', 0, 1, NULL, GETUTCDATE(), 1),
    ('PEN', 'Peruvian Sol', 'S/', 0, 1, NULL, GETUTCDATE(), 1),
    ('ARS', 'Argentine Peso', 'AR$', 0, 1, NULL, GETUTCDATE(), 1),
    ('UYU', 'Uruguayan Peso', '$U', 0, 1, NULL, GETUTCDATE(), 1),
    ('PYG', 'Paraguayan Guaraní', '₲', 0, 1, NULL, GETUTCDATE(), 1),
    ('BOB', 'Bolivian Boliviano', 'Bs', 0, 1, NULL, GETUTCDATE(), 1),
    ('VES', 'Venezuelan Bolívar', 'Bs.S', 0, 1, NULL, GETUTCDATE(), 1),
    ('GTQ', 'Guatemalan Quetzal', 'Q', 0, 1, NULL, GETUTCDATE(), 1),
    ('HNL', 'Honduran Lempira', 'L', 0, 1, NULL, GETUTCDATE(), 1),
    ('NIO', 'Nicaraguan Córdoba', 'C$', 0, 1, NULL, GETUTCDATE(), 1),
    ('CRC', 'Costa Rican Colón', '₡', 0, 1, NULL, GETUTCDATE(), 1),
    ('PAB', 'Panamanian Balboa', 'B/.', 0, 1, NULL, GETUTCDATE(), 1),
    ('DOP', 'Dominican Peso', 'RD$', 0, 1, NULL, GETUTCDATE(), 1),
    ('HTG', 'Haitian Gourde', 'G', 0, 1, NULL, GETUTCDATE(), 1),
    ('CUP', 'Cuban Peso', '$MN', 0, 1, NULL, GETUTCDATE(), 1),
    ('BSD', 'Bahamian Dollar', 'B$', 0, 1, NULL, GETUTCDATE(), 1),
    ('KYD', 'Cayman Islands Dollar', 'CI$', 0, 1, NULL, GETUTCDATE(), 1),
    ('BMD', 'Bermudian Dollar', 'BD$', 0, 1, NULL, GETUTCDATE(), 1),
    ('AWG', 'Aruban Florin', 'Afl', 0, 1, NULL, GETUTCDATE(), 1),
    ('ANG', 'Netherlands Antillean Guilder', 'NAf', 0, 1, NULL, GETUTCDATE(), 1),
    ('XPF', 'CFP Franc', 'CFP', 0, 1, NULL, GETUTCDATE(), 1),
    ('NPR', 'Nepalese Rupee', 'रू', 0, 1, NULL, GETUTCDATE(), 1),
    ('BDT', 'Bangladeshi Taka', '৳', 0, 1, NULL, GETUTCDATE(), 1),
    ('LKR', 'Sri Lankan Rupee', 'රු', 0, 1, NULL, GETUTCDATE(), 1),
    ('MMK', 'Myanmar Kyat', 'K', 0, 1, NULL, GETUTCDATE(), 1),
    ('KHR', 'Cambodian Riel', '៛', 0, 1, NULL, GETUTCDATE(), 1),
    ('LAK', 'Lao Kip', '₭', 0, 1, NULL, GETUTCDATE(), 1),
    ('MNT', 'Mongolian Tögrög', '₮', 0, 1, NULL, GETUTCDATE(), 1),
    ('KZT', 'Kazakhstani Tenge', '₸', 0, 1, NULL, GETUTCDATE(), 1),
    ('UZS', 'Uzbekistani Som', 'so'm', 0, 1, NULL, GETUTCDATE(), 1),
    ('TJS', 'Tajikistani Somoni', 'ЅМ', 0, 1, NULL, GETUTCDATE(), 1),
    ('TMT', 'Turkmenistani Manat', 'T', 0, 1, NULL, GETUTCDATE(), 1),
    ('GEL', 'Georgian Lari', '₾', 0, 1, NULL, GETUTCDATE(), 1),
    ('AMD', 'Armenian Dram', '֏', 0, 1, NULL, GETUTCDATE(), 1),
    ('AZN', 'Azerbaijani Manat', '₼', 0, 1, NULL, GETUTCDATE(), 1),
    ('BYN', 'Belarusian Ruble', 'Br', 0, 1, NULL, GETUTCDATE(), 1),
    ('MDL', 'Moldovan Leu', 'L', 0, 1, NULL, GETUTCDATE(), 1),
    ('UAH', 'Ukrainian Hryvnia', '₴', 0, 1, NULL, GETUTCDATE(), 1),
    ('RSD', 'Serbian Dinar', 'дин', 0, 1, NULL, GETUTCDATE(), 1),
    ('BGN', 'Bulgarian Lev', 'лв', 0, 1, NULL, GETUTCDATE(), 1),
    ('RON', 'Romanian Leu', 'lei', 0, 1, NULL, GETUTCDATE(), 1),
    ('HRK', 'Croatian Kuna', 'kn', 0, 1, NULL, GETUTCDATE(), 1),
    ('ALL', 'Albanian Lek', 'L', 0, 1, NULL, GETUTCDATE(), 1),
    ('MKD', 'Macedonian Denar', 'ден', 0, 1, NULL, GETUTCDATE(), 1),
    ('BAM', 'Bosnia and Herzegovina Convertible Mark', 'KM', 0, 1, NULL, GETUTCDATE(), 1),
    ('MNE', 'Montenegrin Euro', '€', 0, 1, NULL, GETUTCDATE(), 1),
    ('XK', 'Kosovo Euro', '€', 0, 1, NULL, GETUTCDATE(), 1),
    ('ISK', 'Icelandic Króna', 'kr', 1, 1, NULL, GETUTCDATE(), 1),
    ('FJD', 'Fijian Dollar', 'FJ$', 0, 1, NULL, GETUTCDATE(), 1),
    ('WST', 'Samoan Tālā', 'T', 0, 1, NULL, GETUTCDATE(), 1),
    ('TOP', 'Tongan Paʻanga', 'T$', 0, 1, NULL, GETUTCDATE(), 1),
    ('VUV', 'Vanuatu Vatu', 'VT', 0, 1, NULL, GETUTCDATE(), 1),
    ('SBD', 'Solomon Islands Dollar', 'SI$', 0, 1, NULL, GETUTCDATE(), 1),
    ('PGK', 'Papua New Guinean Kina', 'K', 0, 1, NULL, GETUTCDATE(), 1),
    ('KID', 'Kiribati Dollar', '$', 0, 1, NULL, GETUTCDATE(), 1),
    ('TVD', 'Tuvaluan Dollar', '$', 0, 1, NULL, GETUTCDATE(), 1),
    ('NAD', 'Namibian Dollar', 'N$', 0, 1, NULL, GETUTCDATE(), 1),
    ('BWP', 'Botswana Pula', 'P', 0, 1, NULL, GETUTCDATE(), 1),
    ('LSL', 'Lesotho Loti', 'L', 0, 1, NULL, GETUTCDATE(), 1),
    ('SZL', 'Eswatini Lilangeni', 'L', 0, 1, NULL, GETUTCDATE(), 1),
    ('MWK', 'Malawian Kwacha', 'MK', 0, 1, NULL, GETUTCDATE(), 1),
    ('ZMW', 'Zambian Kwacha', 'ZK', 0, 1, NULL, GETUTCDATE(), 1),
    ('MZN', 'Mozambican Metical', 'MT', 0, 1, NULL, GETUTCDATE(), 1),
    ('MUR', 'Mauritian Rupee', '₨', 0, 1, NULL, GETUTCDATE(), 1),
    ('SCR', 'Seychellois Rupee', '₨', 0, 1, NULL, GETUTCDATE(), 1),
    ('DJF', 'Djiboutian Franc', 'Fdj', 0, 1, NULL, GETUTCDATE(), 1),
    ('SOS', 'Somali Shilling', 'S', 0, 1, NULL, GETUTCDATE(), 1),
    ('SDG', 'Sudanese Pound', 'ج.س', 0, 1, NULL, GETUTCDATE(), 1),
    ('SSP', 'South Sudanese Pound', 'SSP', 0, 1, NULL, GETUTCDATE(), 1),
    ('CDF', 'Congolese Franc', 'FC', 0, 1, NULL, GETUTCDATE(), 1),
    ('RWF', 'Rwandan Franc', 'FRw', 0, 1, NULL, GETUTCDATE(), 1),
    ('BIF', 'Burundian Franc', 'FBu', 0, 1, NULL, GETUTCDATE(), 1),
    ('KMF', 'Comorian Franc', 'CF', 0, 1, NULL, GETUTCDATE(), 1),
    ('MGA', 'Malagasy Ariary', 'Ar', 0, 1, NULL, GETUTCDATE(), 1),
    ('MVR', 'Maldivian Rufiyaa', 'Rf', 0, 1, NULL, GETUTCDATE(), 1),
    ('BTN', 'Bhutanese Ngultrum', 'Nu', 0, 1, NULL, GETUTCDATE(), 1),
    ('AFN', 'Afghan Afghani', '؋', 0, 1, NULL, GETUTCDATE(), 1),
    ('IRR', 'Iranian Rial', '﷼', 0, 1, NULL, GETUTCDATE(), 1),
    ('IQD', 'Iraqi Dinar', 'ع.د', 0, 1, NULL, GETUTCDATE(), 1),
    ('KWD', 'Kuwaiti Dinar', 'د.ك', 0, 1, NULL, GETUTCDATE(), 1),
    ('BHD', 'Bahraini Dinar', '.د.ب', 0, 1, NULL, GETUTCDATE(), 1),
    ('QAR', 'Qatari Riyal', 'ر.ق', 0, 1, NULL, GETUTCDATE(), 1),
    ('AED', 'UAE Dirham', 'د.إ', 0, 1, NULL, GETUTCDATE(), 1),
    ('OMR', 'Omani Rial', 'ر.ع.', 0, 1, NULL, GETUTCDATE(), 1),
    ('YER', 'Yemeni Rial', '﷼', 0, 1, NULL, GETUTCDATE(), 1),
    ('SYP', 'Syrian Pound', 'ل.س', 0, 1, NULL, GETUTCDATE(), 1),
    ('LBP', 'Lebanese Pound', 'ل.ل', 0, 1, NULL, GETUTCDATE(), 1),
    ('JOD', 'Jordanian Dinar', 'د.ا', 0, 1, NULL, GETUTCDATE(), 1),
    ('ILS', 'Israeli Shekel', '₪', 0, 1, NULL, GETUTCDATE(), 1),
    ('PAL', 'Palestinian Shekel', '₪', 0, 1, NULL, GETUTCDATE(), 1),
    ('SAR', 'Saudi Riyal', 'ر.س', 0, 1, NULL, GETUTCDATE(), 1),
    ('PKR', 'Pakistani Rupee', '₨', 0, 1, NULL, GETUTCDATE(), 1);

-- SymbolPosition values:
-- 0 = Before (e.g., $100, €100, £100)
-- 1 = After (e.g., 100 kr, 100 Kč)

-- Most currencies use symbol before the value (0)
-- Scandinavian currencies (SEK, NOK, DKK, ISK) use symbol after the value (1)